apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dxurf1qim-go 
  janus-idp.io/tekton: dxurf1qim-go
  backstage.io/kubernetes-id: dxurf1qim-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dxurf1qim-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml